services:

  postgresql:
    image: postgres
    container_name: stitch-connect-db
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: stitchConnect
      POSTGRES_PASSWORD: stitchConnect!
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: stitch-connect-minio
    restart: unless-stopped
    command: minio server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: stitchConnect
      MINIO_ROOT_PASSWORD: stitchConnect!
    volumes:
      - minio_volume:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  postgres_volume:
  minio_volume:
